name: Asset Pallet Generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install screenshot-glb
      run: npm install --save @shopify/screenshot-glb

    - name: Update pallet site
      run: |
        chmod +x scripts/generate_html_gallery.sh
        ./scripts/generate_html_gallery.sh models --head > index.html


    - name: Take screenshots and make pallet
      run: |
        chmod +x scripts/process_files.sh
        ./scripts/process_files.sh models glb png 512 512
        ./scripts/process_files.sh templates glb png 512 512
        ./scripts/generate_html_gallery.sh models --body >> index.html
        ./scripts/generate_html_gallery.sh templates --body --tail >> index.html

    - name: Update README
      run: |
        python scripts/table.py --head > README.md
        python scripts/table.py models >> README.md
        python scripts/table.py templates >> README.md
      

    - name: Commit changes
      run: |
        git config --global user.name "madjin"
        git config --global user.email "32600939+madjin@users.noreply.github.com"
        git add .
        git commit -m "Update READMEs"
        git push
